<?php
/* @var string $this->name */

require_once 'templates/header.phtml';
?>

<div class="md:w-96 sm:w-96 w-full mx-auto mt-5 mb-5 p-7 bg-white shadow-lg shadow-black-500/50">
    <form
        class="flex flex-col box-border"
        action="/contact"
        method="post"
    >

        <label
            for="name"
            class="block text-md my-1 font-medium"
        >
            Abteilungsname
        </label>
        <input
            id="name" type="text"
            name="name"
            class="[appearance:textfield] border-b-2 border-black px-2 mb-5 h-8 focus:outline-none appearance-none"
            placeholder="Abteilungsname"
            value="<?= $this->name ?>"
        >
        <button
            class="
                w-20 h-7 mt-4 bg-white
                self-end font-medium
                uppercase hover:underline
                hover:underline-offset-4
            "
            type="submit"
            name="action"
            value="createDepartment"
        >
            Create
        </button>
    </form>
</div>

<?php require_once 'templates/footer.phtml'; ?>

